export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const UPDATE_SERVICES = "UPDATE_SERVICES";
export const CANCEL_UPDATE = "CANCEL_UPDATE";

export const FETCH_REQUEST = "FETCH_REQUEST";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAILURE = "FETCH_FAILURE";

export const REMOVE_SERVICE_REQUEST = "REMOVE_SERVICE_REQUEST";
export const REMOVE_SERVICE_SUCCESS = "REMOVE_SERVICE_SUCCESS";
export const REMOVE_SERVICE_FAILURE = "REMOVE_SERVICE_FAILURE";

export const ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS";
export const ADD_SERVICE_REQUEST = "ADD_SERVICE_REQUEST";
export const ADD_SERVICE_FAILURE = "ADD_SERVICE_FAILURE";
